---
abstract: 'Mojolicious plugin for integrating Disqus forum'
author:
  - 'Adam Stokes L<adamjs@cpan.org>'
build_requires:
  Mojolicious::Lite: 0
  Test::Mojo: 0
  Test::More: 0
configure_requires:
  Module::Build::Tiny: 0.024
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Disqus-Tiny
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Mojo::Base: 0
  strictures: 1
resources:
  bugtracker: https://github.com/battlemidget/Mojolicious-Plugin-Disqus-Tiny/issues
  homepage: https://github.com/battlemidget/Mojolicious-Plugin-Disqus-Tiny
  repository: https://github.com/battlemidget/Mojolicious-Plugin-Disqus-Tiny.git
version: 1.000
